baseurl = "/"
title = "Space and Coffee"
author = "Jason I. Carter"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

googleAnalytics = "UA-43596308-6"
disqusShortname = "space-and-coffee"

enableRobotsTXT = true
canonifyURLs = true

[params]
  sitename = "Space and Coffee"
  disableWebFonts = false

[params.adsense]
  client = "ca-pub-3168901090832308"
  inArticleSlot = "12345"

[[menu.main]]
    name = "About"
    url  = "/about/"
[[menu.main]]
    name = "Contact"
    url  = "/contact/"
